"""renamed column in music_tracks

Revision ID: 2013a8a5daf5
Revises: e3bdac6eaca5
Create Date: 2022-08-23 21:28:25.146233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2013a8a5daf5'
down_revision = 'e3bdac6eaca5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_tracks', sa.Column('extension', sa.String(), nullable=False))
    op.drop_column('music_tracks', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_tracks', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('music_tracks', 'extension')
    # ### end Alembic commands ###
