"""adding music tracks second migration, because forgot to add entities

Revision ID: 21116a58f1a9
Revises: c95ef15a822d
Create Date: 2022-08-23 19:05:20.447630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21116a58f1a9'
down_revision = 'c95ef15a822d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
