"""initial

Revision ID: 281440012342
Revises: 
Create Date: 2022-08-04 23:30:49.525371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281440012342'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
