"""initial

Revision ID: 413d56aef601
Revises: 
Create Date: 2022-08-05 23:47:53.035118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413d56aef601'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name', nullable=False, new_column_name='username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username', nullable=False, new_column_name='name')
    # ### end Alembic commands ###
