"""added MusicTracksModel,MusicTracksFolderModel migration

Revision ID: e3bdac6eaca5
Revises: 3a1ef86ebb50
Create Date: 2022-08-23 19:14:22.056600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bdac6eaca5'
down_revision = '3a1ef86ebb50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_name', sa.String(length=100), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_tracks_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_tracks_folders')
    op.drop_table('music_tracks')
    # ### end Alembic commands ###
